POST http://localhost:8000/api/v1/order
Content-Type: application/json

{
  "prix_commande": 50,
  "statut_commande" : "prise",
  "table_commande_id": {
    "id": 1
  },
  "serveur_id": {
    "id" : 39
  },
  "client": "titi"
}